xlinters-settings:
  golint:
    min-confidence: 0.1

linters:
  # TODO: best practice is to enable specific linters
  enable-all: true
  disable:
    - funlen
    - goerr113
    - gofumpt
    - gomnd
    - godot
    - testpackage
    - nolintlint
    - golint
    - scopelint
    - gosec

    # Disabled after upgrading golangci-lint
    # Enable them after issues are resolved
    - gofmt
    - goimports
    - exhaustruct
    - exhaustivestruct
    - forcetypeassert
    - gosimple
    - ifshort
    - nlreturn
    - nosnakecase
    - paralleltest
    - thelper
    - varnamelen
    - wrapcheck
