xlinters-settings:
  golint:
    min-confidence: 0.1

linters:
  # TODO: best practice is to enable specific linters
  enable-all: true
  disable:
    - funlen
    - err113
    - gofumpt
    - godot
    - testpackage
    - nolintlint
    - gosec
    - depguard

    # Disabled after upgrading golangci-lint
    # Enable them after issues are resolved
    - gofmt
    - goimports
    - exhaustruct
    - forcetypeassert
    - gosimple
    - nlreturn
    - paralleltest
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
